### ISSUE TITLE
Could not show like introduction

### ISSUE THREAD

**Issue by trinhcanhphuc** [sbis04/yoga-instructor#12]
I couldn't see any data like your introduction: [https://github.com/sbis04/yoga-instructor/raw/master/screenshots/new_ui/sofia_layer_2_2.png](https://github.com/sbis04/yoga-instructor/raw/master/screenshots/new_ui/sofia_layer_2_2.png)

This is my current screen:
[https://imgur.com/guTo8Rb](https://imgur.com/guTo8Rb)

This is my console:
`Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
V/MiuiFrameworkFactory(27271): get AllImpl object = android.common.MiuiFrameworkFactoryImpl@d70d67
W/MirrorManager(27271): this model don't Support
I/Timeline(27271): Timeline: Activity_launch_request time:17960380
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityCreated
I/Timeline(27271): Timeline: Activity_launch_request time:17960427
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityStarted
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityResumed
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityResumed
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityResumed
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityStopped
W/System  (27271): Ignoring header X-Firebase-Locale because its value was null.
W/System  (27271): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(27271): Notifying id token listeners about user ( u4r6JcZt8hP7sHbP5J1vsyma9jQ2 ).
D/FirebaseAuth(27271): Notifying auth state listeners about user ( u4r6JcZt8hP7sHbP5J1vsyma9jQ2 ).
I/flutter (27271): GENDER: Male
I/flutter (27271): DONE Selecting
I/flutter (27271): Trịnh
W/DynamiteModule(27271): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(27271): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(27271): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/vikbiswas.sofi(27271): The ClassLoaderContext is a special shared library.
I/vikbiswas.sofi(27271): The ClassLoaderContext is a special shared library.
V/NativeCrypto(27271): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...
W/vikbiswas.sofi(27271): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/TetheringManager(27271): registerTetheringEventCallback:com.souvikbiswas.sofia
I/ProviderInstaller(27271): Installed default security provider GmsCore_OpenSSL
W/vikbiswas.sofi(27271): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/vikbiswas.sofi(27271): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/vikbiswas.sofi(27271): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/vikbiswas.sofi(27271): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/vikbiswas.sofi(27271): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/vikbiswas.sofi(27271): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/vikbiswas.sofi(27271): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
I/flutter (27271): User info exists: true
I/flutter (27271): DATA:
I/flutter (27271): {uid: u4r6JcZt8hP7sHbP5J1vsyma9jQ2, imageUrl: https://lh3.googleusercontent.com/a-/AOh14GiRQS4-dSGwkxn9akUGJTBJhQg5uSzVILwoUlNp=s96-c, userName: Trịnh, gender: Male, age: 20 - 34}
I/flutter (27271): User Info updated in the database
I/flutter (27271): USER DATA: Instance of 'User'
I/flutter (27271): false
V/MediaPlayer(27271): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(27271): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(27271): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(27271): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter (27271): true
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityResumed
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityResumed
W/RenderInspector(27271): QueueBuffer time out on com.souvikbiswas.sofia/com.souvikbiswas.sofia.MainActivity, count=1, avg=15 ms, max=15 ms.
W/RenderInspector(27271): DequeueBuffer time out on com.souvikbiswas.sofia/com.souvikbiswas.sofia.MainActivity, count=1, avg=14 ms, max=14 ms.
I/AudiofileplayerPlugin(27271): LifecycleCallbacks.onActivityStopped
W/System  (27271): A resource failed to call release. 
W/vikbiswas.sofi(27271): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)`

**Comment by sbis04** [comment]
It's because the Firestore database is not public, and if you want to just try the app use the `.apk` file link present in the Readme. **This repo is still not accepting any public contribution.**
